#!/bin/bash

# this is the script that gets called by cron
# it executes the subscriptiondownloader node app

export PATH=/opt/node/bin:$PATH
export NODE_PATH=/opt/node/bin/node/node_modules

cd /home/pi/github/nodejs-feed
node background/subscriptiondownload > background/subscriptiondownload.output
